from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_VERSION = "v0.1.0"
RELEASE_TITLE = "CAPAS Claim Gate v0.1.0 - local evidence-typed claim gate MVP"


def _run(command: list[str], check: bool = False) -> tuple[int, str]:
    proc = subprocess.run(command, cwd=ROOT, text=True, capture_output=True)
    output = (proc.stdout + proc.stderr).strip()
    if check and proc.returncode:
        raise RuntimeError(f"{' '.join(command)} failed:\n{output}")
    return proc.returncode, output


def _release_generated_paths(version: str) -> set[str]:
    return {
        f"outputs/github_release_plan_{version}.json",
        f"outputs/release_notes_{version}.md",
        "outputs/capas_claim_gate_ui.html",
        "outputs/capas_product_demo_report.json",
        "outputs/capas_product_demo_report.md",
        "outputs/external_claim_accept_decision.json",
        "outputs/external_claim_hold_decision.json",
        "outputs/external_claim_rewrite_decision.json",
        "outputs/external_input_schema_report.json",
        "outputs/external_user_validation_report.json",
        "outputs/fresh_clone_install_report.json",
        "outputs/profile_registration_readiness_report.json",
        "outputs/release_readiness_report.json",
    }


def _filtered_status(version: str) -> tuple[int, str]:
    code, output = _run(["git", "status", "--short"])
    ignored = _release_generated_paths(version)
    lines = []
    for line in output.splitlines():
        parts = line.split(maxsplit=1)
        path = parts[1] if len(parts) == 2 else line[3:] if len(line) > 3 else line
        if path not in ignored:
            lines.append(line)
    return code, "\n".join(lines)


def _release_notes(version: str) -> str:
    return f"""# {RELEASE_TITLE}

This is a local MVP release candidate for CAPAS Claim Gate.

## What this release is

- A package-installable CLI: `capas`
- A small external claim/evidence JSON surface
- A published MVP input schema: `docs/schema/capas_claim_payload.schema.json`
- A static local review UI generated by `capas ui`
- A readiness packet for external scientific-computation reviewers
- A local CAPAS Physical Evidence profile packet for RO-Crate/Workflow Run RO-Crate alignment
- CI gates for product demo, input schema, fresh source checkout install, profile validation, and RO-Crate coverage

## What this release is not

- Not fine-tune ready
- Not a new provenance standard
- Not proof of broad LLM scientific reasoning
- Not a simulator benchmark claim
- Not external user validation
- Not formal RO-Crate profile registration

## Verified local gates

Run:

```bash
python -m pip install -e .
capas demo
capas schema
capas check-input --input examples/external_claim_accept.json
capas decide --input examples/external_claim_rewrite.json
capas validate
python benchmarks/verify_external_mvp_readiness.py
```

Expected release-readiness status before publication:

```text
release_ready: False
missing until external setup: git remote, {version} tag, valid GitHub CLI authentication
```

## Honest scope

CAPAS prevents scientific-computation traces from licensing claims larger than
their evidence type supports. It emits `ACCEPT`, `REWRITE`, `REJECT`, or `HOLD`
over explicit evidence fields. It is a rule gate, not an LLM judge.
"""


def _write_release_files(version: str, execute: bool) -> dict[str, object]:
    release_notes_path = ROOT / "outputs" / f"release_notes_{version}.md"
    release_plan_path = ROOT / "outputs" / f"github_release_plan_{version}.json"
    release_notes = _release_notes(version)

    remote_code, remote_output = _run(["git", "remote", "-v"])
    auth_code, auth_output = _run(["gh", "auth", "status"])
    tag_code, tag_output = _run(["git", "tag", "--list", version])
    status_code, status_output = _filtered_status(version)
    branch_code, branch_output = _run(["git", "branch", "--show-current"])

    plan = {
        "version": version,
        "execute": execute,
        "release_title": RELEASE_TITLE,
        "release_notes": str(release_notes_path.relative_to(ROOT)),
        "commands_execute_mode": [
            "python benchmarks/verify_external_mvp_readiness.py",
            "git status --short",
            "git push origin HEAD",
            f"git tag {version} (only if missing)",
            f"git push origin {version}",
            f"gh release create {version} --title {RELEASE_TITLE!r} --notes-file {release_notes_path.relative_to(ROOT)}",
        ],
        "preflight": {
            "git_remote_configured": {
                "passed": remote_code == 0 and bool(remote_output.strip()),
                "detail": remote_output or "no git remote configured",
            },
            "github_cli_authenticated": {
                "passed": auth_code == 0,
                "detail": auth_output or "gh auth status produced no output",
            },
            "tag_exists": {
                "passed": version in tag_output.splitlines(),
                "detail": tag_output or "tag not present; execute mode can create it after gates pass",
            },
            "worktree_clean": {
                "passed": status_code == 0 and not status_output.strip(),
                "detail": status_output or "clean",
            },
            "current_branch": {
                "passed": branch_code == 0 and bool(branch_output.strip()),
                "detail": branch_output or "no current branch",
            },
        },
        "non_degradation": (
            "This file is a release plan, not evidence of publication. Publication "
            "requires remote push, tag push, GitHub Actions pass, and a GitHub release URL."
        ),
    }
    plan["ready_to_execute"] = (
        plan["preflight"]["git_remote_configured"]["passed"]
        and plan["preflight"]["github_cli_authenticated"]["passed"]
        and plan["preflight"]["worktree_clean"]["passed"]
        and plan["preflight"]["current_branch"]["passed"]
    )
    release_notes_path.parent.mkdir(parents=True, exist_ok=True)
    release_notes_path.write_text(release_notes, encoding="utf-8")
    release_plan_path.write_text(json.dumps(plan, indent=2, sort_keys=True), encoding="utf-8")
    return plan


def _execute_release(version: str, plan: dict[str, object]) -> None:
    if not plan["ready_to_execute"]:
        raise RuntimeError("release preflight is not ready; inspect outputs/github_release_plan_v0.1.0.json")

    _run([sys.executable, "benchmarks/verify_external_mvp_readiness.py"], check=True)
    status_code, status_output = _filtered_status(version)
    if status_code or status_output.strip():
        raise RuntimeError(f"worktree changed during preflight:\n{status_output}")

    _run(["git", "push", "origin", "HEAD"], check=True)
    tag_code, tag_output = _run(["git", "tag", "--list", version])
    if version not in tag_output.splitlines():
        _run(["git", "tag", version], check=True)
    _run(["git", "push", "origin", version], check=True)

    notes_path = ROOT / "outputs" / f"release_notes_{version}.md"
    release_code, release_output = _run([
        "gh",
        "release",
        "create",
        version,
        "--title",
        RELEASE_TITLE,
        "--notes-file",
        str(notes_path),
    ])
    if release_code:
        if "already_exists" in release_output or "already exists" in release_output.lower():
            _run(["gh", "release", "edit", version, "--title", RELEASE_TITLE, "--notes-file", str(notes_path)], check=True)
        else:
            raise RuntimeError(f"gh release create failed:\n{release_output}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Prepare or publish the CAPAS GitHub release.")
    parser.add_argument("--version", default=DEFAULT_VERSION)
    parser.add_argument("--execute", action="store_true", help="mutate git/GitHub: push, tag, and create release")
    args = parser.parse_args()

    plan = _write_release_files(args.version, execute=args.execute)
    if args.execute:
        _execute_release(args.version, plan)
        print(f"published {args.version}")
    else:
        print(f"release dry-run written for {args.version}")
        print(f"ready_to_execute: {plan['ready_to_execute']}")
        print(f"plan: outputs/github_release_plan_{args.version}.json")
        print(f"notes: outputs/release_notes_{args.version}.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
